# Generated by Django 4.0.5 on 2022-07-22 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Contact us',
            },
        ),
        migrations.CreateModel(
            name='DashboardCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cash', models.CharField(max_length=60)),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('soil', models.CharField(default='loam', max_length=20)),
                ('humidity', models.IntegerField(default=0)),
                ('temp', models.IntegerField(default=0)),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('description', models.CharField(default='N/A', max_length=500)),
                ('email', models.EmailField(default='farm@abontem.com', max_length=254)),
                ('whatsapp', models.CharField(default='0245003234', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Finance Page',
            },
        ),
        migrations.CreateModel(
            name='FrontForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Homepage Signup form',
            },
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=10)),
                ('contact', models.IntegerField(default=10)),
                ('email', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'Investment Requests',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(default='farm@abontem.com', max_length=254)),
                ('whatsapp', models.CharField(default='0245003234', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Farm Management',
            },
        ),
        migrations.CreateModel(
            name='MostCultivated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=20, unique=True)),
                ('hectares', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Most Cultivated',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('description', models.CharField(default='N/A', max_length=500)),
                ('email', models.EmailField(default='farm@abontem.com', max_length=254)),
                ('whatsapp', models.CharField(default='0245003234', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Farm Products',
            },
        ),
    ]
