# Generated by Django 4.0.5 on 2022-06-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=20)),
                ('cash', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
