# Generated by Django 4.0.5 on 2022-06-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
    ]
