# Generated by Django 4.0.5 on 2022-06-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_crops'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crops',
            new_name='Crop',
        ),
    ]
