# Generated by Django 4.0.5 on 2022-07-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_rename_cash_dashboardcrop_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcrop',
            name='humidity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dashboardcrop',
            name='temp',
            field=models.CharField(max_length=10),
        ),
    ]
