# Generated by Django 4.0.5 on 2022-06-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_crop_humidity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('size', models.IntegerField(default=0)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
