# Generated by Django 4.0.5 on 2022-06-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_rename_crops_crop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='crop_name',
            new_name='name',
        ),
    ]
