# Generated by Django 4.0.5 on 2022-06-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_land'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
