# Generated by Django 4.0.5 on 2022-07-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_dashboardcrop_humidity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Payment Details',
            },
        ),
    ]
