# Generated by Django 4.0.5 on 2022-06-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_alter_land_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_no', models.IntegerField(default=10)),
                ('project_no', models.IntegerField(default=10)),
                ('blog_no', models.IntegerField(default=10)),
                ('forest_no', models.IntegerField(default=10)),
            ],
        ),
    ]
