# Generated by Django 4.0.6 on 2022-08-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_paymentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='whatsapp',
            field=models.CharField(default='0553612697', max_length=10),
        ),
    ]
