# Generated by Django 4.0.5 on 2022-06-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_stat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crop',
            new_name='DashboardCrop',
        ),
        migrations.RenameModel(
            old_name='Land',
            new_name='DashboardLand',
        ),
        migrations.RenameModel(
            old_name='Stat',
            new_name='DashboardStat',
        ),
    ]
