# Generated by Django 4.0.6 on 2022-08-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_alter_management_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financepage',
            name='whatsapp',
            field=models.CharField(default='0553612697', max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='whatsapp',
            field=models.CharField(default='0553612697', max_length=10),
        ),
    ]
