# Generated by Django 4.0.5 on 2022-06-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_rename_crop_dashboardcrop_rename_land_dashboardland_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardStat',
        ),
    ]
