# Generated by Django 4.0.5 on 2022-06-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_delete_dashboardstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=10)),
                ('contact', models.IntegerField(default=10)),
                ('email', models.IntegerField(default=10)),
            ],
        ),
    ]
