# Generated by Django 4.0.5 on 2022-06-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invest',
            options={'verbose_name_plural': 'Invest Requests'},
        ),
    ]
