# Generated by Django 4.0.5 on 2022-06-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_rename_finance_management_alter_management_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='email',
            field=models.EmailField(default='farm@abontem.com', max_length=254),
        ),
        migrations.AddField(
            model_name='management',
            name='whatsapp',
            field=models.CharField(default='0245003234', max_length=10),
        ),
        migrations.AlterField(
            model_name='management',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
