# Generated by Django 4.0.5 on 2022-06-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_management_email_management_whatsapp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(default='farm@abontem.com', max_length=254)),
                ('whatsapp', models.CharField(default='0245003234', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Farm Products',
            },
        ),
        migrations.AlterModelOptions(
            name='frontform',
            options={'verbose_name_plural': 'Homepage Signup form'},
        ),
        migrations.AlterModelOptions(
            name='invest',
            options={'verbose_name_plural': 'Investment Requests'},
        ),
    ]
