# Generated by Django 4.0.5 on 2022-06-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_farmproducts_alter_frontform_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FarmProducts',
            new_name='Products',
        ),
    ]
