# Generated by Django 4.0.5 on 2022-06-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_rename_farmproducts_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
