# Generated by Django 4.0.5 on 2022-06-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_alter_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('coo', models.CharField(default='N/A', max_length=500)),
                ('wind', models.EmailField(default='farm@abontem.com', max_length=254)),
                ('cloud', models.CharField(default='0245003234', max_length=10)),
                ('atmosphere', models.IntegerField()),
                ('condition', models.CharField(max_length=20)),
                ('temp', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Weather',
            },
        ),
    ]
