# Generated by Django 4.0.5 on 2022-06-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0018_remove_weather_atmosphere_remove_weather_cloud_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weather',
            new_name='Forecast',
        ),
    ]
