# Generated by Django 4.0.5 on 2022-06-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_rename_weather_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('description', models.CharField(default='N/A', max_length=500)),
                ('email', models.EmailField(default='farm@abontem.com', max_length=254)),
                ('whatsapp', models.CharField(default='0245003234', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Finance Page',
            },
        ),
    ]
