# Generated by Django 4.0.5 on 2022-06-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0020_financepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
