# Generated by Django 4.0.5 on 2022-06-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
