# Generated by Django 4.0.5 on 2022-06-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0024_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactPage',
        ),
    ]
