# Generated by Django 4.0.5 on 2022-07-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0026_hometemp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeTemp',
        ),
    ]
