# Generated by Django 4.0.5 on 2022-07-04 16:44

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0027_delete_hometemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='name',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='country',
            field=django_countries.fields.CountryField(default='Ghana', max_length=2),
        ),
    ]
