# Generated by Django 4.0.5 on 2022-07-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0028_remove_contactpage_name_contactpage_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostCultivated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('hectares', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Most Cultivated',
            },
        ),
    ]
