# Generated by Django 4.0.5 on 2022-07-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0029_mostcultivated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostcultivated',
            name='hectares',
            field=models.CharField(max_length=100),
        ),
    ]
