# Generated by Django 4.0.5 on 2022-07-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0031_rename_name_mostcultivated_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
