# Generated by Django 4.0.5 on 2022-07-07 16:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0033_alter_contactpage_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='country',
            field=django_countries.fields.CountryField(default='Kenya', max_length=2),
        ),
    ]
