# Generated by Django 4.0.5 on 2022-07-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0034_alter_contactpage_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='country',
            field=models.CharField(default='Ghana', max_length=50),
        ),
    ]
