# Generated by Django 4.0.5 on 2022-07-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0035_alter_contactpage_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
